cask_args appdir: "/Applications"

brew 'git'
brew 'python@3.9'
brew 'go'
brew 'nodebrew'
brew 'fish'
brew 'ffmpeg'
brew 'mtr'
brew 'nmap'
brew 'telnet'
brew 'wget'
brew 'curl'
brew 'tree'
brew 'sl'
# tap 'heroku/brew'
# brew 'heroku'

cask 'shiftit' #画面分割するやつ
cask 'scroll-reverser'
cask 'clipy'
cask 'wireshark'
cask 'adobe-creative-cloud'
cask 'docker'
cask 'termius'
cask 'visual-studio-code'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'google-drive'
cask 'firefox'
cask 'zoomus'
cask 'vlc'
cask 'discord'
# cask 'slack'
# cask 'coteditor'
